
function gca = formatPlot(gca,x,y,t)

        
hTitle  = title (t);
hXLabel = xlabel(x);
hYLabel = ylabel(y);

set( gca                       , ...
    'FontName'   , 'Helvetica Neue' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica Neue');
% set([hLegend, gca]             , ...
%      'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          );
set( hTitle                    , ...
    'FontSize'   , 13          , ...
    'FontWeight' , 'bold'      );
set( gca                                    , ...
            'Box'         , 'off'           , ...
            'TickDir'     , 'out'           , ...
            'TickLength'  , [.02 .02]       , ...
            'XMinorTick'  , 'on'            , ...
            'YMinorTick'  , 'on'            , ...
            'YGrid'       , 'off'           , ...
            'XColor'      , [.3 .3 .3]      , ...
            'YColor'      , [.3 .3 .3]      , ...
            'LineWidth'   , 1               );
end


